name = "bestb"
main = "src/worker.ts"
compatibility_date = "2025-11-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "manlove", id = "79027c6280ce481b9989d6c99811d7a1" }
]
